In [1]:
import os
os.getcwd()

'C:\\Users\\SRADHA\\Desktop\\Project\\Bank Dataset'

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [3]:
dataset=pd.read_csv('Bank-data.csv')
dataset.head()

Index  interest_rate  credit  Gender  previous  duration Churn
0      0          1.334       0       1         0       117    no
1      1          0.767       0       0         1       274   yes
2      2          4.858       0       1         0       167    no
3      3          4.120       0       0         0       686   yes
4      4          4.856       0       1         0       159    no

In [4]:
dataset['Churn']=dataset['Churn'].astype('category')
dataset['Churn']=dataset['Churn'].cat.codes

In [5]:
# Splitting the data into independent and dependent variables
x=dataset.drop(['Churn'],axis=1)
y=dataset['Churn']

In [6]:
x.head()

Index  interest_rate  credit  Gender  previous  duration
0      0          1.334       0       1         0       117
1      1          0.767       0       0         1       274
2      2          4.858       0       1         0       167
3      3          4.120       0       0         0       686
4      4          4.856       0       1         0       159

In [7]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Churn, dtype: int8

In [8]:
# Split into training and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=1)

# Logistic Regression 

In [9]:
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()
logit.fit(x_train,y_train)

LogisticRegression()

In [10]:
y_pred_test_logit=logit.predict(x_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [12]:
print(classification_report(y_test,y_pred_test_logit))

              precision    recall  f1-score   support

           0       0.86      0.94      0.90        69
           1       0.93      0.82      0.87        61

    accuracy                           0.88       130
   macro avg       0.89      0.88      0.88       130
weighted avg       0.89      0.88      0.88       130



In [13]:
print(confusion_matrix(y_test,y_pred_test_logit))

[[65  4]
 [11 50]]


In [14]:
print(accuracy_score(y_test,y_pred_test_logit))

0.8846153846153846


# Principal Component Analysis

In [15]:
from sklearn.decomposition import PCA
pca=PCA(n_components=None)   # None means all values
x_train_n=pca.fit_transform(x_train)
x_test_n=pca.fit_transform(x_test)

In [16]:
pd.DataFrame(x_train_n)

0           1         2         3         4         5
0   -133.275216  218.199956  1.430737 -0.183875 -0.113061 -0.014365
1   -229.738719   58.237411  2.173167 -0.217112 -0.036184 -0.014870
2     17.904255  131.930421 -1.828381 -0.208726 -0.324426 -0.079339
3    -94.358638  260.375079 -1.719726 -0.176496 -0.339712 -0.068122
4   -293.187143   -8.413217  2.001713  0.759624  0.083901  0.045998
..          ...         ...       ...       ...       ...       ...
383 -126.656730 -125.019591 -1.507354 -0.262703 -0.261719 -0.095975
384  257.576721 -118.286614  1.971776  0.719370  0.108172  0.042539
385  -82.893722 -182.977248  1.997703 -0.275842 -0.006436 -0.036112
386  757.419483  -38.017278 -1.873596 -0.267850 -0.288487 -0.085901
387 -313.593313 -213.020681  1.064175 -0.276510 -0.070189 -0.058159

[388 rows x 6 columns]

In [17]:
explained_variance=pca.explained_variance_ratio_

In [18]:
explained_variance

array([8.21090925e-01, 1.78877574e-01, 2.90760395e-05, 1.74063800e-06,
       5.33010532e-07, 1.50409984e-07])

In [19]:
pca=PCA(n_components=2)  
x_train_2=pca.fit_transform(x_train)
x_test_2=pca.fit_transform(x_test)

In [20]:
pd.DataFrame(x_train_2)

0           1
0   -133.275216  218.199956
1   -229.738719   58.237411
2     17.904255  131.930421
3    -94.358638  260.375079
4   -293.187143   -8.413217
..          ...         ...
383 -126.656730 -125.019591
384  257.576721 -118.286614
385  -82.893722 -182.977248
386  757.419483  -38.017278
387 -313.593313 -213.020681

[388 rows x 2 columns]

In [21]:
logit_1=LogisticRegression()
logit_1.fit(x_train_2,y_train)

LogisticRegression()

In [22]:
y_pred_test_logit_pca=logit_1.predict(x_test_2)

In [23]:
print(classification_report(y_test,y_pred_test_logit_pca))

              precision    recall  f1-score   support

           0       0.72      0.83      0.77        69
           1       0.76      0.64      0.70        61

    accuracy                           0.74       130
   macro avg       0.74      0.73      0.73       130
weighted avg       0.74      0.74      0.74       130



In [24]:
print(confusion_matrix(y_test,y_pred_test_logit_pca))

[[57 12]
 [22 39]]


In [25]:
print(accuracy_score(y_test,y_pred_test_logit_pca))

0.7384615384615385


# K-fold Method- To improve Accuracy

In [26]:
from sklearn.model_selection import cross_val_score
accuracy=cross_val_score(logit_1,x_train_2,y_train,cv=15)
accuracy

array([0.73076923, 0.69230769, 0.73076923, 0.76923077, 0.69230769,
       0.53846154, 0.65384615, 0.5       , 0.73076923, 0.92307692,
       0.73076923, 0.5       , 0.73076923, 0.56      , 0.64      ])

In [27]:
accuracy[9]

0.9230769230769231

# Naive Bayes Model

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier_nb=GaussianNB()
classifier_nb.fit(x_train_2,y_train)

GaussianNB()

In [29]:
y_pred_nb=classifier_nb.predict(x_test_2)

In [30]:
print(accuracy_score(y_test,y_pred_nb))

0.7692307692307693


In [33]:
accuracy_nb=cross_val_score(classifier_nb,x_test_2,y_test,cv=10)
accuracy_nb

array([0.76923077, 0.84615385, 0.53846154, 1.        , 0.69230769,
       0.76923077, 0.92307692, 0.84615385, 0.69230769, 0.61538462])

In [34]:
accuracy_nb[6]

0.9230769230769231